# 最终版：修复所有兼容性问题
name: Build Docker Offline Package for CentOS 7 (Final)

on:
  workflow_dispatch:

jobs:
  build-package:
    runs-on: ubuntu-latest
    container: centos:7

    steps:
      # 第1步：修正源并准备环境 (此步骤不变，已经验证是正确的)
      - name: 修正源并准备环境
        run: |
          sed -i 's/mirrorlist/#mirrorlist/' /etc/yum.repos.d/CentOS-Base.repo
          sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Base.repo
          yum install -y epel-release yum-utils curl # 新增安装 curl
          yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          yum clean all
          yum makecache

      # 第2步：下载所有依赖包 (此步骤不变)
      - name: 下载Docker及其所有依赖
        run: |
          mkdir docker-packages
          yumdownloader --resolve --destdir=./docker-packages \
            docker-ce \
            docker-ce-cli \
            containerd.io \
            docker-buildx-plugin \
            docker-compose-plugin
      
      # 第3步：打包所有RPM文件 (此步骤不变)
      - name: 打包所有RPM文件
        run: |
          cd docker-packages
          tar -czvf ../DOCKER_CENTOS7_OFFLINE_PACK.tar.gz .

      # 第4步：【全新方法】上传到中转站并打印下载链接
      - name: 上传到临时中转站
        run: |
          echo "--- 开始上传文件，请在日志中查找最终的下载链接 ---"
          # 使用 curl 将文件上传到 transfer.sh，它会返回一个下载链接
          curl --upload-file ./DOCKER_CENTOS7_OFFLINE_PACK.tar.gz https://transfer.sh/DOCKER_CENTOS7_OFFLINE_PACK.tar.gz
          echo "" # 打印一个空行方便查看
          echo "--- 上传完成，请复制上面的链接进行下载！链接14天内有效。 ---"
